services:
  - type: static
    name: adelixmediascam
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: serve
        source: /sitemap.xml
        destination: /sitemap.xml
      - type: rewrite
        source: /*
        destination: /index.html